name: LAMS Validation

on:
  pull_request:
  push:

jobs:
  lams_job:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout LookML
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install LAMS
        run: npm install -g @looker/look-at-me-sideways@5

      - name: Run LAMS
        run: |
          lams \
            --reporting=save-no \
            --output=github-job-summary